package com.example.agentdemo.workflow.governance;

public enum WorkflowEvaluationAssertionType {
    STATIC_RULE_BLOCK_ABSENT,
    PATH_NODE_TYPES_INCLUDE_IN_ORDER,
    PATH_NODE_TYPES_EXCLUDE,
    TOOL_SUCCEEDED,
    TOOL_FAILED,
    TOOL_OUTPUT_FIELD_EQUALS,
    PARSED_FIELDS_INCLUDE,
    FINAL_OUTPUT_CUSTOMER_READABLE,
    FINAL_OUTPUT_CONTAINS_ANY,
    FINAL_OUTPUT_CONTAINS_ALL,
    FINAL_OUTPUT_EXCLUDES
}
