-- Per-call token usage, associated with a run (and optionally the originating app). Used for the
-- run detail usage summary and the Runs/Logs view. owner_id keeps it owner-isolated.

create table usage_records (
    id bigint generated by default as identity primary key,
    run_id varchar(64) not null,
    app_id varchar(64),
    owner_id varchar(128) not null,
    provider varchar(64),
    model varchar(128),
    prompt_tokens integer,
    completion_tokens integer,
    total_tokens integer,
    created_at timestamp(6) with time zone not null
);

create index idx_usage_records_owner_run on usage_records (owner_id, run_id);
create index idx_usage_records_owner_app_created on usage_records (owner_id, app_id, created_at desc);
