-- Knowledge Base product layer, added additively over the existing rag_documents pipeline.
-- Existing documents keep kb_id = NULL and remain retrievable through the legacy /api/rag/* API;
-- documents ingested through /api/knowledge-bases carry a kb_id and per-source metadata. No data
-- is dropped or moved.

create table knowledge_bases (
    id bigint generated by default as identity primary key,
    kb_id varchar(64) not null unique,
    owner_id varchar(128) not null,
    name varchar(128) not null,
    description varchar(1024),
    retrieval_config_json text,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null
);
create index idx_knowledge_bases_owner_created on knowledge_bases (owner_id, created_at desc, id desc);

alter table rag_documents add column kb_id varchar(64);
alter table rag_documents add column source_type varchar(16);
alter table rag_documents add column file_name varchar(256);
alter table rag_documents add column mime_type varchar(128);
alter table rag_documents add column size_bytes bigint;
alter table rag_documents add column content_hash varchar(64);
alter table rag_documents add column error_message text;

create index idx_rag_documents_owner_kb_status on rag_documents (owner_id, kb_id, index_status);
