create table workflow_http_credentials (
    id bigint generated by default as identity primary key,
    credential_id varchar(64) not null unique,
    owner_id varchar(128) not null,
    name varchar(128) not null,
    type varchar(32) not null,
    encrypted_payload text not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null
);

create index idx_workflow_http_credentials_owner_created
    on workflow_http_credentials (owner_id, created_at desc);
