-- Baseline schema for the agent-backend-demo PostgreSQL database.
--
-- This represents the schema as it existed before the index-status / outbox / row-version work
-- (V2). It is only executed on a brand-new database; existing databases are stamped at this
-- version via spring.flyway.baseline-on-migrate and only receive V2 onwards.
--
-- Large text/JSON columns use `text` (Hibernate maps these @JdbcTypeCode(LONGVARCHAR) fields to
-- text on PostgreSQL). NOTE for legacy upgrades: a database originally created by Hibernate
-- ddl-auto on an older build may have these as `oid` (large objects); converting oid -> text is a
-- data migration that must be performed manually before adopting this baseline.

create table conversation_messages (
    id bigint generated by default as identity primary key,
    conversation_id varchar(128) not null,
    role varchar(16) not null,
    content text not null,
    created_at timestamp(6) with time zone not null
);

create table rag_documents (
    id bigint generated by default as identity primary key,
    title varchar(256),
    content text not null,
    created_at timestamp(6) with time zone not null
);

create table rag_document_chunks (
    id bigint generated by default as identity primary key,
    document_id bigint not null,
    chunk_index integer not null,
    vector_id varchar(128) not null unique,
    content text not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null
);

create table runs (
    run_id varchar(64) not null primary key,
    type varchar(32) not null,
    status varchar(32) not null,
    input text not null,
    output text,
    error_message text,
    started_at timestamp(6) with time zone not null,
    ended_at timestamp(6) with time zone
);
create index idx_runs_status_started_at on runs (status, started_at);
create index idx_runs_type_started_at on runs (type, started_at);

create table run_steps (
    step_id varchar(64) not null primary key,
    run_id varchar(64) not null,
    node_name varchar(128) not null,
    input_json text not null,
    output_json text,
    error_message text,
    status varchar(32) not null,
    started_at timestamp(6) with time zone not null,
    ended_at timestamp(6) with time zone
);
create index idx_run_steps_run_started_at on run_steps (run_id, started_at);

create table workflow_definitions (
    id bigint generated by default as identity primary key,
    definition_id varchar(64) not null unique,
    name varchar(128) not null,
    description varchar(512),
    definition_json text not null,
    version integer not null,
    status varchar(32) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null
);

create table workflow_definition_revisions (
    id bigint generated by default as identity primary key,
    definition_id varchar(64) not null,
    version integer not null,
    status varchar(32) not null,
    name varchar(128) not null,
    description varchar(512),
    definition_json text not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint uq_workflow_definition_revisions_def_version unique (definition_id, version)
);

create table workflow_run_records (
    run_id varchar(64) not null primary key,
    definition_id varchar(64) not null,
    definition_version integer not null,
    started_at timestamp(6) with time zone not null
);
