-- Expand-only migration for the index-status / outbox / optimistic-locking work.
-- Safe to run against an existing baseline database: adds nullable columns first, backfills,
-- then tightens constraints (expand-contract).

-- 1. rag_documents.index_status (async indexing state surfaced by the API).
alter table rag_documents add column index_status varchar(32);
-- Existing rows already have their content persisted and are therefore keyword-retrievable.
-- Backfill them as READY. For a DashVector-backed deployment, reconcile against the vector store
-- afterwards (documents whose vectors cannot be confirmed should be re-indexed).
update rag_documents set index_status = 'READY' where index_status is null;
alter table rag_documents alter column index_status set not null;

-- 2. workflow_definitions.row_version (JPA @Version optimistic locking).
alter table workflow_definitions add column row_version bigint not null default 0;

-- 3. Transactional outbox for asynchronous DashVector upserts/deletes.
create table vector_outbox_events (
    id bigint generated by default as identity primary key,
    type varchar(32) not null,
    status varchar(32) not null,
    document_id bigint not null,
    payload_json text not null,
    attempts integer not null,
    next_attempt_at timestamp(6) with time zone not null,
    last_error varchar(2048),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null
);
-- Supports the worker's claim query (status + next_attempt_at + created order).
create index idx_vector_outbox_claim on vector_outbox_events (status, next_attempt_at, created_at, id);
