-- Audit trail for management (control-plane) and runtime actions.
--
-- owner_id and request_id are additions beyond the base spec: owner_id keeps the console audit
-- view owner-isolated like every other user-visible table, and request_id lets an audit row be
-- correlated with logs/traces via the X-Request-Id header. No prompts or secrets are stored here;
-- only action metadata (see AuditService / SecretRedactor).

create table audit_logs (
    id bigint generated by default as identity primary key,
    owner_id varchar(128) not null,
    actor_type varchar(32) not null,
    actor_id varchar(128) not null,
    action varchar(64) not null,
    resource_type varchar(64),
    resource_id varchar(128),
    ip varchar(64),
    user_agent varchar(256),
    request_id varchar(64),
    success boolean not null,
    error_code varchar(64),
    created_at timestamp(6) with time zone not null
);

create index idx_audit_logs_owner_created on audit_logs (owner_id, created_at desc, id desc);
create index idx_audit_logs_owner_resource on audit_logs (owner_id, resource_type, resource_id);
