-- Application (product) layer: a published app binds an immutable revision snapshot so historical
-- runs stay reproducible. Single-tenant: owner_id keeps apps owner-isolated like every other table.

create table apps (
    id bigint generated by default as identity primary key,
    app_id varchar(64) not null unique,
    owner_id varchar(128) not null,
    name varchar(128) not null,
    description varchar(1024),
    type varchar(32) not null,
    status varchar(32) not null,
    config_json text,
    workflow_definition_id varchar(64),
    workflow_definition_version integer,
    version integer not null,
    published_version integer,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    row_version bigint not null default 0
);
create index idx_apps_owner_created on apps (owner_id, created_at desc, id desc);

create table app_revisions (
    id bigint generated by default as identity primary key,
    app_id varchar(64) not null,
    owner_id varchar(128) not null,
    version integer not null,
    status varchar(32) not null,
    snapshot_json text not null,
    created_at timestamp(6) with time zone not null,
    constraint uq_app_revisions_app_version unique (app_id, version)
);
create index idx_app_revisions_owner_app_version on app_revisions (owner_id, app_id, version desc);

-- Associate runs with the originating app (nullable: direct chat/workflow/agent runs have no app).
alter table runs add column app_id varchar(64);
create index idx_runs_owner_app_started_at on runs (owner_id, app_id, started_at desc);
