-- Runtime API keys for business integrations. Only the SHA-256 hash of the key is stored; the
-- plaintext is shown once at creation and never persisted. A key authenticates only the runtime
-- endpoints of its own app (never the console management API).

create table app_api_keys (
    id bigint generated by default as identity primary key,
    key_id varchar(64) not null unique,
    app_id varchar(64) not null,
    owner_id varchar(128) not null,
    key_hash varchar(128) not null unique,
    name varchar(128),
    scopes varchar(256) not null,
    status varchar(16) not null,
    created_at timestamp(6) with time zone not null,
    last_used_at timestamp(6) with time zone,
    revoked_at timestamp(6) with time zone
);

create index idx_app_api_keys_owner_app on app_api_keys (owner_id, app_id, created_at desc);
create index idx_app_api_keys_hash_status on app_api_keys (key_hash, status);
